In [1]:
import pandas as pd
import numpy as np
from io import StringIO

#Create a data as a CSV format and convert into data frame


In [ ]:
csv_data = '''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
0.0,11.0,12.0'''
df = pd.read_csv(StringIO(csv_data)) #Read a comma-separated values (csv) file into DataFrame
df                                   #Pandas DataFrame is a two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns)

A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   NaN  8.0
2  0.0  11.0  12.0  NaN

In [ ]:
df.describe()

A          B          C         D
count  3.000000   3.000000   2.000000  2.000000
mean   2.000000   6.333333   7.500000  6.000000
std    2.645751   4.509250   6.363961  2.828427
min    0.000000   2.000000   3.000000  4.000000
25%    0.500000   4.000000   5.250000  5.000000
50%    1.000000   6.000000   7.500000  6.000000
75%    3.000000   8.500000   9.750000  7.000000
max    5.000000  11.000000  12.000000  8.000000

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

# Check whether the data is null or not / NaN

In [ ]:
df.B.unique()


array([ 2.,  6., 11.])

In [ ]:
df.B.nunique()


3

In [ ]:
df['D'].value_counts()


4.0    1
8.0    1
Name: D, dtype: int64

In [ ]:
df.isnull() #Dataframe of Boolean values which are True for NaN values 

A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

# Find the number of NaN in each column of s data frame


In [ ]:
#df.isnull().sum() 
df.isnull().sum(axis=0)

A    0
B    0
C    1
D    1
dtype: int64

In [ ]:
df.isnull().sum(axis=1)

0    0
1    1
2    1
dtype: int64

#Dataframe into numpy representation


In [ ]:
result = df.values
print(result)


[[ 1.  2.  3.  4.]
 [ 5.  6. nan  8.]
 [ 0. 11. 12. nan]]


# Remove the missing values

In [ ]:
df

A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   NaN  8.0
2  0.0  11.0  12.0  NaN

In [ ]:
df.dropna()

A    B    C    D
0  1.0  2.0  3.0  4.0

In [ ]:
df.dropna(axis=1)

A     B
0  1.0   2.0
1  5.0   6.0
2  0.0  11.0

In [ ]:
df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [ ]:
new_row = {'A':np.nan, 'B':np.nan, 'C':np.nan, 'D':np.nan}
#append row to the dataframe
df= df.append(new_row, ignore_index=True)

df

df.isnull()
#df.drop([3])

<ipython-input-19-a550d8ce60bd>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df= df.append(new_row, ignore_index=True)


A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True
3   True   True   True   True

In [ ]:
# only drop rows where all columns are NaN
df.dropna(how='all')


A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   NaN  8.0
2  0.0  11.0  12.0  NaN

In [ ]:
# drop rows that do not have at least 4 non-NaN values
df.dropna(thresh=4)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [ ]:
# only drop rows where NaN appear in specific columns (here: 'C')
df.dropna(subset=['C'])

A     B     C    D
0  1.0   2.0   3.0  4.0
2  0.0  11.0  12.0  NaN

In [ ]:
df
df.drop([2],inplace=True)

In [ ]:
df

A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   NaN  8.0
2  0.0  11.0  12.0  NaN

# Fill the missing values

In [ ]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values = np.nan, strategy ='me') 
imputer = imputer.fit(df) 

print("Original Data : \n", df) 
# Imputing the data      
data = imputer.transform(df) 

print("Imputed Data : \n", data) 
df_new=pd.DataFrame(data=data, index=["0","1","2"], columns=["A", "B","C","D"])


InvalidParameterError: ignored

In [ ]:
df_new

NameError: ignored

In [ ]:
df

A    B    C    D
0  1.0  2.0  3.0  4.0
1  5.0  6.0  NaN  8.0

#Read a CSV File and fillna 

In [ ]:
from google.colab import files #Share nba.csv file
uploaded = files.upload()

KeyboardInterrupt: ignored

In [ ]:
import io 
df_nba = pd.read_csv(io.BytesIO(uploaded['nba.csv'])) 
print(df_nba)

              Name            Team  ...            College     Salary
0    Avery Bradley  Boston Celtics  ...              Texas  7730337.0
1      Jae Crowder  Boston Celtics  ...          Marquette  6796117.0
2     John Holland  Boston Celtics  ...  Boston University        NaN
3      R.J. Hunter  Boston Celtics  ...      Georgia State  1148640.0
4    Jonas Jerebko  Boston Celtics  ...                NaN  5000000.0
..             ...             ...  ...                ...        ...
453   Shelvin Mack       Utah Jazz  ...             Butler  2433333.0
454      Raul Neto       Utah Jazz  ...                NaN   900000.0
455   Tibor Pleiss       Utah Jazz  ...                NaN  2900000.0
456    Jeff Withey       Utah Jazz  ...             Kansas   947276.0
457            NaN             NaN  ...                NaN        NaN

[458 rows x 9 columns]


In [ ]:
df_nba.head(10)

Name            Team  Number  ... Weight            College      Salary
0  Avery Bradley  Boston Celtics     0.0  ...  180.0              Texas   7730337.0
1    Jae Crowder  Boston Celtics    99.0  ...  235.0          Marquette   6796117.0
2   John Holland  Boston Celtics    30.0  ...  205.0  Boston University         NaN
3    R.J. Hunter  Boston Celtics    28.0  ...  185.0      Georgia State   1148640.0
4  Jonas Jerebko  Boston Celtics     8.0  ...  231.0                NaN   5000000.0
5   Amir Johnson  Boston Celtics    90.0  ...  240.0                NaN  12000000.0
6  Jordan Mickey  Boston Celtics    55.0  ...  235.0                LSU   1170960.0
7   Kelly Olynyk  Boston Celtics    41.0  ...  238.0            Gonzaga   2165160.0
8   Terry Rozier  Boston Celtics    12.0  ...  190.0         Louisville   1824360.0
9   Marcus Smart  Boston Celtics    36.0  ...  220.0     Oklahoma State   3431040.0

[10 rows x 9 columns]

In [ ]:
#df_nba["College"].fillna("No College",inplace = True)
#df_nba.head(10)
df_nba["College"].fillna( method ='bfill') 
df_nba["Salary"].fillna( method ='ffill', inplace = True) 
#df_nba["College"].fillna( method ='ffill', limit = 1, inplace = True) 
df_nba.head(20)

Name            Team  ...            College      Salary
0             Avery Bradley  Boston Celtics  ...              Texas   7730337.0
1               Jae Crowder  Boston Celtics  ...          Marquette   6796117.0
2              John Holland  Boston Celtics  ...  Boston University   6796117.0
3               R.J. Hunter  Boston Celtics  ...      Georgia State   1148640.0
4             Jonas Jerebko  Boston Celtics  ...                NaN   5000000.0
5              Amir Johnson  Boston Celtics  ...                NaN  12000000.0
6             Jordan Mickey  Boston Celtics  ...                LSU   1170960.0
7              Kelly Olynyk  Boston Celtics  ...            Gonzaga   2165160.0
8              Terry Rozier  Boston Celtics  ...         Louisville   1824360.0
9              Marcus Smart  Boston Celtics  ...     Oklahoma State   3431040.0
10          Jared Sullinger  Boston Celtics  ...         Ohio State   2569260.0
11            Isaiah Thomas  Boston Celtics  ...         Washington   6912869.0
12              Evan Turner  Boston Celtics  ...         Ohio State   3425510.0
13              James Young  Boston Celtics  ...           Kentucky   1749840.0
14             Tyler Zeller  Boston Celtics  ...     North Carolina   2616975.0
15         Bojan Bogdanovic   Brooklyn Nets  ...                NaN   3425510.0
16             Markel Brown   Brooklyn Nets  ...     Oklahoma State    845059.0
17          Wayne Ellington   Brooklyn Nets  ...     North Carolina   1500000.0
18  Rondae Hollis-Jefferson   Brooklyn Nets  ...            Arizona   1335480.0
19             Jarrett Jack   Brooklyn Nets  ...       Georgia Tech   6300000.0

[20 rows x 9 columns]

# Categorical data set

In [ ]:
df_cat = pd.DataFrame([
['green', 'M', 10.1, 'class1'],
['red', 'L', 13.5, 'class2'],
['blue', 'XL', 15.3, 'class1']])
df_cat

0   1     2       3
0  green   M  10.1  class1
1    red   L  13.5  class2
2   blue  XL  15.3  class1

In [ ]:
df_cat.columns

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df_cat.columns = ['color', 'size', 'price', 'classlabel']
df_cat

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [ ]:
size_mapping = {'XL': 3, 'L': 2, 'M': 1}
df_cat['size'] = df_cat['size'].map(size_mapping)
df_cat

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [ ]:
size_mapping.items()

dict_items([('XL', 3), ('L', 2), ('M', 1)])

In [ ]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}
inv_size_mapping

{1: 'M', 2: 'L', 3: 'XL'}

In [ ]:
df_cat['size'] = df_cat['size'].map(inv_size_mapping)
df_cat

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [ ]:
np.unique(df_cat['classlabel'])

array(['class1', 'class2'], dtype=object)

In [ ]:
class_mapping = {label:idx for idx,label in
                 enumerate(np.unique(df_cat['classlabel']))}
class_mapping

{'class1': 0, 'class2': 1}

In [ ]:
df_cat['classlabel'] = df_cat['classlabel'].map(class_mapping)
df_cat

color size  price  classlabel
0  green    M   10.1           0
1    red    L   13.5           1
2   blue   XL   15.3           0

In [ ]:
inv_class_mapping = {v: k for k, v in class_mapping.items()}
df_cat['classlabel'] = df_cat['classlabel'].map(inv_class_mapping)
df_cat

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

#Label Encoding


In [ ]:
from sklearn.preprocessing import LabelEncoder
class_label_encoder = LabelEncoder()
y = class_label_encoder.fit_transform(df_cat['classlabel'].values)
y


array([0, 1, 0])

In [ ]:
class_label_encoder.inverse_transform(y)

array(['class1', 'class2', 'class1'], dtype=object)

In [ ]:
X = df_cat[['color', 'size', 'price']].values
X

array([['green', 'M', 10.1],
       ['red', 'L', 13.5],
       ['blue', 'XL', 15.3]], dtype=object)

In [ ]:
color_label_encoder = LabelEncoder()
X[:, 0] = color_label_encoder.fit_transform(X[:, 0])
X

array([[1, 'M', 10.1],
       [2, 'L', 13.5],
       [0, 'XL', 15.3]], dtype=object)

In [ ]:
size_mapping = {'XL': 3, 'L': 2, 'M': 1}
df_cat['size'] = df_cat['size'].map(size_mapping)
X = df_cat[['color', 'size', 'price']].values
X

array([['green', 1, 10.1],
       ['red', 2, 13.5],
       ['blue', 3, 15.3]], dtype=object)

In [ ]:
color_label_encoder = LabelEncoder()
X[:, 0] = color_label_encoder.fit_transform(X[:, 0])
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [ ]:
pd.get_dummies(df_cat[['price', 'color', 'size']])

price  size  color_blue  color_green  color_red
0   10.1     1           0            1          0
1   13.5     2           0            0          1
2   15.3     3           1            0          0

In [ ]:
df_cat

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

#One Hot Encoding

In [ ]:
pd.get_dummies(df_cat[['price', 'color', 'size','classlabel']])

price  size  color_blue  ...  color_red  classlabel_class1  classlabel_class2
0   10.1     1           0  ...          0                  1                  0
1   13.5     2           0  ...          1                  0                  1
2   15.3     3           1  ...          0                  1                  0

[3 rows x 7 columns]

In [ ]:
df_cat_new = pd.DataFrame([
['green', 'M', 10.1, 'class1'],
['red', 'L', 13.5, 'class2'],
['blue', 'XL', 15.3, 'class1']])
df_cat_new

0   1     2       3
0  green   M  10.1  class1
1    red   L  13.5  class2
2   blue  XL  15.3  class1

In [ ]:
pd.get_dummies(df_cat_new)

2  0_blue  0_green  0_red  1_L  1_M  1_XL  3_class1  3_class2
0  10.1       0        1      0    0    1     0         1         0
1  13.5       0        0      1    1    0     0         0         1
2  15.3       1        0      0    0    0     1         1         0